export const USER_CONNECTED = 'USER_CONNECTED'
export const USER_DISCONNECTED = 'USER_DISCONNECTED'

export const PRIVATE_MESSAGE = 'PRIVATE_MESSAGE'
export const USERS = 'USERS'
export const USER_ONLINE = 'USER_ONLINE'
export const USER_OFFLINE = 'USER_OFFLINE'
